{% set version = "1.23" %}
{% set name = "lcalc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: http://oto.math.uwaterloo.ca/~mrubinst/L_function_public/CODE/L-{{ version }}.tar.gz
  sha256: 3d1f47bdb3156c085faab3c4ccaaf68063175d3fba9b4c85adea52d032bcd46a
  patches:
    - patches/clang.patch
    - patches/lcalc-1.23_default_parameters_1.patch
    - patches/lcalc-1.23_default_parameters_2.patch
    - patches/Lcommon.h.patch
    - patches/Makefile.patch
    - patches/pari-2.7.patch
    - patches/time.h.patch
    - patches/include_pari.patch
    - patches/typeof.diff

build:
  number: 1002
  skip: true  # [win]

requirements:
  build:
    - libtool
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - pari
    - gmp
    - mpfr
  run:
    - pari
    - gmp
    - mpfr

test:
  commands:
    - test -f ${PREFIX}/include/libLfunction/L.h
    - test -f ${PREFIX}/lib/libLfunction.dylib     # [osx]
    - test -f ${PREFIX}/lib/libLfunction.so        # [linux]

about:
  home: http://oto.math.uwaterloo.ca/~mrubinst/L_function_public/L.html
  license: GPLv2+
  license_file: COPYING
  summary: C++ L-function class library and command line interface

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
