{% set version = "2.0.5" %}
{% set name = "lcalc" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://gitlab.com/sagemath/{{ name }}/-/archive/{{ version }}/{{ name }}-{{ version }}.tar.gz
  sha256: c64b7284d688cf8986a64bbf0bc802f6efc70c26693fd0d6e3f155b90d5e5a95

build:
  number: 3
  skip: true  # [win]
  run_exports:
    # The last patch releases did not contain breaking ABI changes, so x.x
    # seems to be reasonable.
    - {{ pin_subpackage("lcalc", max_pin="x.x") }}

requirements:
  build:
    - libtool
    - make
    - autoconf
    - automake
    - pkg-config
    - gengetopt
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - pari
    - gmp
    - mpfr

test:
  commands:
    - test -f ${PREFIX}/include/lcalc/L.h
    - test -f ${PREFIX}/lib/libLfunction.dylib     # [osx]
    - test -f ${PREFIX}/lib/libLfunction.so        # [linux]

about:
  home: https://gitlab.com/sagemath/lcalc
  license: GPL-2.0-or-later
  license_file: doc/COPYING
  summary: C++ L-function class library and command line interface

extra:
  recipe-maintainers:
    - isuruf
    - saraedum
