travis:
  secure:
    BINSTAR_TOKEN: FprReMKuY6Pslve0NZPnkA5OmKY3Ume06EWk6cJZ1GCqTuSUBv5GAJZRZhI5gBJ+ptkW+iRxGfg39jlKoA0scg+GKeiFYwjwAW/CRenmRLBqEQqP1oJvUmBYR1LRSuVv5QgIBS+BczE1NUpCpzDr/2YMaMZkXtvZa8EfMVBKNteEzz3mLa94aRUeL9EswTiSWAPQhabqs3ThTER80mj13ZMRG+j7sFDpEHEuHN6xo3fWMciw56pVdQ5JQshc/Q+GCNhDoDwdgSyT0Oj2PC/+9zHK5cZlLgyd62ml0j6JKFv4H2Oa66+nPU/WOBhDe5humrKxevoQ2vuYcIxIii/hYFCT4TflmIB9IChc28ojNFqFNNtMjUdaEno61cDiaEKPSw6ruOZFF0baPXFq/WjUGXktUMPX1AFmOnNDNbWciS204lw+iuJQHXmGf9hETIcCYoBIBu5vzzsdTU40XGHBuIQ84tBEw8jbzJRs1qwhVXt5g7QZ5Fzl3aIrf3JtdKN1G46/+HIVu5JSLBOI/Fy4EKY86uJsz3Nw3w1DU9EBi6pZC7ryaUmvdnp3jEFTJOu7js/8L+MSQ9fZMNuVyWhR6NvFXoaPafsiJD+xD57tzXAmotPCakr+7/FlfSeGI6B5D+xQz1rJSWXwCQapgv5fzSkS7zfLt0A8OCudphI433k=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
